sudo: false
language: node_js

node_js:
- '10'

addons:
  ssh_known_hosts: jschallenge.vreshch.com

script:
- npm install
- docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
- docker build --pull -t "vreshch/codenjoy-lb" .
- docker push "vreshch/codenjoy-lb"


notifications:
  email: false
