server:
  servlet.context-path: ${context:/codenjoy-contest}
  ip: 127.0.0.1

rest-sender:
  pool-size: 100

mvc:
  cache-period: 259200
  screen-servlet-path: /screen-ws/*
  control-servlet-path: /ws/*


game:
  save.auto: true
  ai: true
board.save.ticks: 1
log.debug: false
page:
  main:
    url: ''
  registration:
    url: ''
    nickname: true
  help.language: ''
email:
  verification: false
  password: ''
  name: info@codenjoy.com
  hash: secureSoul
donate.code:
database:
  url: ''
  name: ''
  user: ''
  password: ''
admin.password: admin

app:
  logging:
    - com.epam.dojo
    - com.codenjoy

