server:
  servlet.context-path: ${context:/codenjoy-contest}
  ip: 127.0.0.1

rest-sender:
  pool-size: 100

mvc:
  cache-period: 259200
  screen-servlet-path: /screen-ws/*
  control-servlet-path: /ws/*


game:
  save.auto: true
  ai: true
board.save.ticks: 1
log.debug: false
registration:
    nickname:
      allowed: false
    pasword:
      min-length: 8
page:
  main:
    url: ''
  registration:
    url: ''
    nickname: true
  login:
    url: ''
  admin:
    url: ''
  help.language: ''
email:
  verification: false
  password: ''
  name: info@codenjoy.com
  hash: secureSoul
donate.code:
database:
  url: ''
  name: ''
  user: ''
  password: ''
admin:
  login: admin@dojarena.io
  password: admin

app:
  logging:
    - com.epam.dojo
    - com.codenjoy

logging:
  level:
    root: info
    com:
      codenjoy: debug
      epam.dojo: debug
      org.eclipse.jetty: debug
