auth-server:
  location: http://localhost:9999/auth

spring:
  security:
    oauth2:
      client:
        registration:
          codebattle-oidc:
            client-id: codebattle
            client-secret: jmOnxA6lqmeUYTDbVcBmndFJNYQ0W9vc
            client-authentication-method: basic
            authorization-grant-type: authorization_code
            redirect-uri-template: "{baseUrl}/login/oauth2/code/{registrationId}"
            #            scope: read, openid
            scope: read
            client-name: codebattle
        provider:
          codebattle-oidc:
            authorization-uri: ${auth-server.location}/oauth/authorize
            token-uri: ${auth-server.location}/oauth/token
            jwk-set-uri: ${auth-server.location}/oauth/client_info
            user-info-uri: ${auth-server.location}/user/me
            user-name-attribute: name